### ISSUE TITLE
the readme example doesn't work...

### ISSUE THREAD

**Issue by nextmood** [zencephalon/Tactful_Tokenizer#1]
> > m.tokenize_text returns ...
> > NoMethodError: undefined method `is_upper_case?' for 83:Fixnum
> >     from /Library/Ruby/Gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:120:in`get_features'

fixed by changing w2[0] with w2[0,1] in line 120 ... i guess it's matter or ruby version. I'm running ruby 1.8.7

**Comment by ghost** [comment]
Hey nextmood, 

This is indeed an issue with 1.8.7. Another way of fixing it is changing <code>w2[0]</code> to <code>w2[0].char</code>. This is slightly safer for dealing with multibyte characters, although it is still unsafe. I'll be updating this library soon with the XML compatibility changes, and I'll try to address this issue at the same time.

**Comment by nextmood** [comment]
thanks for the answer SlyShy. i'll be watching your Github for update.
