### ISSUE TITLE
Right brackets are lost during tokenization

### ISSUE THREAD

**Issue by louismullie** [zencephalon/Tactful_Tokenizer#10]
Right brackets are lost from text after the following Regexp is applied: `(?-mix:(.)(?=[?!\)";}\]*:@\.'])|(?=[\)}\]])(.)|(.)(?=[({\[])|((^|\s)-)(?=[^-]))`.

Input sentence:

These have been interpreted as reports of unidentified flying objects (UFOs), but may just as well describe meteors, and, since Obsequens, probably, writes in the 4th century, that is, some 400 years after the events he describes, they hardly qualify as eye-witness accounts.

Before Regexp:

These have been interpreted as reports of unidentified flying objects ( UFOs), but may just as well describe meteors, and, since Obsequens, probably, writes in the 4th century, that is, some 400 years after the events he describes, they hardly qualify as eye-witness accounts.

After Regexp:

These have been interpreted as reports of unidentified flying objects ( UFOs  , but may just as well describe meteors, and, since Obsequens, probably, writes in the 4th century, that is, some 400 years after the events he describes, they hardly qualify as eye-witness accounts .

**Comment by zencephalon** [comment]
@louismullie, thanks for reporting this, I'll look into it.

**Comment by zencephalon** [comment]
@louismullie I added a test case based on the input you provided. It seems like this isn't an issue anymore.
