### ISSUE TITLE
Is this too beta to depend on?

### ISSUE THREAD

**Issue by jakl** [zencephalon/Tactful_Tokenizer#16]
My team would like to use this for some things on translate.twitter.com but I noticed the version number is only 0.0.5 which usually indicates alpha/beta quality, for early-adopters only. Should we wait until version 1.0.0 is released to use this with our production data?

**Comment by changok** [comment]
+1

**Comment by zencephalon** [comment]
@jakl @changok Misleading version number in this case. People have used this in production for four years now, that I know of.
