### ISSUE TITLE
sentence segmentation issue 

### ISSUE THREAD

**Issue by jetset** [zencephalon/Tactful_Tokenizer#2]
Hi , I have the following string and the segmentation fails .
s="1. Sentence one.\n2. Sentence two.\n3. Sentence three.\n"
TOKENIZER.tokenize_text(s)

> > ["1.", "Sentence one.", "2.", "Sentence two.", "3.", "Sentence three."]

when I try 
s="1.Sentence one.\n2.Sentence two.\n3.Sentence three.\n"
I get the right result 
["1.Sentence one.", "2.Sentence two.", "3.Sentence three."]

Can this be fixed ?

**Comment by ghost** [comment]
This should be fixable.

**Comment by ghost** [comment]
Here's the fix

```
require "tactful_tokenizer"
m = TactfulTokenizer::Model.new; nil
m.feats["w1_<NUM>."] = 0
m.tokenize_text("1. Sentence one.\n2. Sentence two.\n3. Sentence three.\n")
=> ["1. Sentence one.", "2. Sentence two.", "3. Sentence three."]
```

**Comment by jetset** [comment]
cool! thanks .
